# Generated by Django 5.2.8 on 2025-11-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='doc',
            field=models.FileField(default='', upload_to='docs', verbose_name='Documentos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='', upload_to='photos', verbose_name='Foto'),
            preserve_default=False,
        ),
    ]
